### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [JanusDG/Homework_0_2nd_term#1]
Ціль дуже не чітка - Навчити можель аналізувати та передбачати дані використовуючи деякі бібліотеки пайтона. Якщо вже є коефіцієнт популярності пісень то що Ви будете обчислювати? Музичні API використовує Корабльова А можете об'єднати зусилля.

Тема: Обчислення популярності пісень.

**Comment by JanusDG** [comment]
Доброго дня, я вже добавив перелік тих бібліотек, які збираюсь використовувати

**Comment by JanusDG** [comment]
@anrom7 Доброго дня, я вже добавив перелік тих бібліотек(дз0 пункт 4), які збираюсь використовувати. Щодо того що я буду обчислювати - то та, я буду обчислювати вже відомі наперед коефіціенти. Проте у частині що відповідає дз2 було сказано - ці дані будуть порівняні з тими що будуть згенеровані за допомогою навчальної моделі(адже існують інші характеристики пісень в яких існує кореляція з їхньою популярністю(жанр, виконавець, мова, тощо)) таким чином матиму наглядні дані про обчислюватиму точність моделі.
